apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: meme-app

data:
  POSTGRES_HOST: "postgres"
  RABBITMQ_HOST: "rabbitmq"
  MINIO_INTERNAL_ENDPOINT: "http://minio:9000"
  MINIO_BUCKET: "memes"
  MINIO_EXTERNAL_ENDPOINT: "http://minio.meme.local"