name: Build and Deploy to K8s
on:
  push:
    branches:
      - main
    paths:
      - 'source-code/**'
      - '.github/workflows/**'
permissions:
  contents: write
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./source-code
          file: ./source-code/frontend/Dockerfile
          push: true
          tags: |
            sterben007/meme-frontend:latest
            sterben007/meme-frontend:${{ steps.vars.outputs.sha_short }}

      - name: Build and push API
        uses: docker/build-push-action@v5
        with:
          context: ./source-code
          file: ./source-code/api/Dockerfile
          push: true
          tags: |
            sterben007/meme-backend:latest
            sterben007/meme-backend:${{ steps.vars.outputs.sha_short }}

      - name: Build and push Worker
        uses: docker/build-push-action@v5
        with:
          context: ./source-code
          file: ./source-code/worker/Dockerfile
          push: true
          tags: |
            sterben007/meme-worker:latest
            sterben007/meme-worker:${{ steps.vars.outputs.sha_short }}

      - name: Update Kubernetes Manifests
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          sed -i "s|image: sterben007/meme-frontend:.*|image: sterben007/meme-frontend:${{ steps.vars.outputs.sha_short }}|g" k8s-gitops/03-apps.yaml
          sed -i "s|image: sterben007/meme-backend:.*|image: sterben007/meme-backend:${{ steps.vars.outputs.sha_short }}|g" k8s-gitops/03-apps.yaml
          sed -i "s|image: sterben007/meme-worker:.*|image: sterben007/meme-worker:${{ steps.vars.outputs.sha_short }}|g" k8s-gitops/03-apps.yaml
          git status
          git pull origin main --no-edit
          git add k8s-gitops/03-apps.yaml
          git commit -m "Update Docker images tag to ${{ steps.vars.outputs.sha_short }}"
          git push